import type { ContributionPoint } from './feature-registry';
export const contributionLabels: Record<ContributionPoint, string> = {
  'toolbar.global': '应用快捷操作',
  'toolbar.canvas': '画布 → 绘图工具',
  'panel.project': '项目 → 素材与合成',
  'panel.scene': '图层 → 创建与结构',
  'panel.inspector.transform': '属性 → 变换',
  'panel.inspector.appearance': '属性 → 外观',
  'panel.inspector.text': '属性 → 文字',
  'panel.inspector.geometry': '属性 → 几何与样式',
  'panel.inspector.effects': '属性 → 效果与遮罩',
  'panel.inspector.structure': '属性 → 父子级',
  'panel.inspector.time': '属性 → 图层时间',
  'panel.inspector.3d': '属性 → 三维与摄像机',
  'panel.inspector.semantic': '属性 → 语义信息',
  'timeline.header': '时间轴 → 播放与导航',
  'timeline.layerContext': '时间轴 → 图层右键',
  'timeline.propertyContext': '时间轴 → 属性右键',
  'timeline.keyframeContext': '时间轴 → 关键帧右键',
  'motion.toolbar': '曲线编辑器',
  'motion.segmentContext': '曲线编辑器 → 区间右键',
  'graph.nodeContext': '合成节点 → 右键',
  'menu.file': '文件',
  'menu.edit': '编辑',
  'menu.layer': '图层',
  'menu.animation': '动画',
  'menu.view': '视图',
  'menu.window': '窗口',
  'menu.help': '帮助',
  'context.canvas': '画布 → 图层右键',
  'context.layer': '图层 → 右键',
  'context.property': '属性 → 右键',
  'context.keyframe': '关键帧 → 右键',
  'context.asset': '项目 → 素材右键',
  'context.node': '合成节点 → 右键',
  commandPalette: '命令搜索',
  'assistant.actions': '助手',
  'dialog.actions': '当前对话框',
};
